"""Change plan draft generator — produces a migration plan from high-severity impacts."""

from collections import defaultdict

from scry.models.changes import ChangeRecord, SchemaChange
from scry.models.config import ProjectConfig
from scry.models.enums import Criticality, Severity
from scry.models.impact import ImpactItem


def _severity_rank(severity: Severity) -> int:
    return {
        Severity.CRITICAL: 4,
        Severity.HIGH: 3,
        Severity.MEDIUM: 2,
        Severity.LOW: 1,
        Severity.INFO: 0,
    }[severity]


def _item_title(item: ImpactItem) -> str:
    if isinstance(item.change, SchemaChange):
        return item.change.path
    return item.change.title


def _item_description(item: ImpactItem) -> str:
    if isinstance(item.change, SchemaChange):
        return item.change.message
    return item.change.description


def _md_cell(value: str) -> str:
    """Escape pipe characters for markdown table cells."""
    return value.replace("|", "\\|")


def _change_type_label(item: ImpactItem) -> str:
    if isinstance(item.change, SchemaChange):
        return item.change.change_type.value
    return item.change.category.value


def _extract_version(impacts: list[ImpactItem]) -> str:
    """Extract the target version from the highest-severity impact."""
    sorted_impacts = sorted(
        impacts, key=lambda i: _severity_rank(i.severity), reverse=True
    )
    for item in sorted_impacts:
        if isinstance(item.change, ChangeRecord) and item.change.version:
            return item.change.version
    return "upcoming"


def generate_change_plan(
    impacts: list[ImpactItem], config: ProjectConfig
) -> str:
    """Generate a markdown change plan draft for high-severity impacts."""
    version = _extract_version(impacts)
    lines: list[str] = []

    # Header
    lines.append(f"# Change Plan Draft -- {version} Migration")
    lines.append("")
    lines.append("> Auto-generated by scry. Requires human review before execution.")
    lines.append("")

    # Scope
    deadlines = [i.deadline for i in impacts if i.deadline is not None]
    earliest_deadline = min(deadlines) if deadlines else None

    lines.append("## Scope")
    lines.append("")
    lines.append(f"- **Target version**: {version}")
    if earliest_deadline:
        lines.append(f"- **Earliest deadline**: {earliest_deadline}")
    lines.append("")

    # Affected Files table
    file_map: dict[str, tuple[Severity, str, str]] = {}
    for item in impacts:
        change_type = _change_type_label(item)
        description = _item_description(item)
        for fpath in item.affected_files:
            fstr = str(fpath)
            if fstr not in file_map or _severity_rank(item.severity) > _severity_rank(
                file_map[fstr][0]
            ):
                file_map[fstr] = (item.severity, change_type, description)

    if file_map:
        lines.append("## Affected Files")
        lines.append("")
        lines.append("| File | Change Type | Severity | Description |")
        lines.append("|---|---|---|---|")
        for fpath, (severity, change_type, description) in sorted(file_map.items()):
            lines.append(
                f"| {fpath} | {change_type} | {severity.value.upper()} | {_md_cell(description)} |"
            )
        lines.append("")

    # Suggested Milestones
    feature_groups: dict[str, list[ImpactItem]] = defaultdict(list)
    ungrouped: list[ImpactItem] = []

    for item in impacts:
        if item.affected_features:
            for feature in item.affected_features:
                feature_groups[feature].append(item)
        else:
            ungrouped.append(item)

    lines.append("## Suggested Milestones")
    lines.append("")

    if feature_groups:
        for idx, (feature, items) in enumerate(feature_groups.items(), 1):
            lines.append(f"### M{idx:02d} -- {feature}")
            lines.append("")
            lines.append("| Task | File | Action | Summary |")
            lines.append("|---|---|---|---|")
            for task_idx, item in enumerate(items, 1):
                file_str = (
                    ", ".join(str(f) for f in item.affected_files)
                    if item.affected_files
                    else "TBD"
                )
                lines.append(
                    f"| {task_idx} | {file_str} | Update | {_md_cell(_item_description(item))} |"
                )
            lines.append("")
    else:
        # Group by severity instead
        severity_groups: dict[Severity, list[ImpactItem]] = defaultdict(list)
        for item in impacts:
            severity_groups[item.severity].append(item)

        idx = 1
        for severity in (
            Severity.CRITICAL,
            Severity.HIGH,
            Severity.MEDIUM,
            Severity.LOW,
            Severity.INFO,
        ):
            items = severity_groups.get(severity, [])
            if not items:
                continue
            lines.append(f"### M{idx:02d} -- {severity.value.upper()} items")
            lines.append("")
            lines.append("| Task | File | Action | Summary |")
            lines.append("|---|---|---|---|")
            for task_idx, item in enumerate(items, 1):
                file_str = (
                    ", ".join(str(f) for f in item.affected_files)
                    if item.affected_files
                    else "TBD"
                )
                lines.append(
                    f"| {task_idx} | {file_str} | Update | {_md_cell(_item_description(item))} |"
                )
            lines.append("")
            idx += 1

    # Handle ungrouped items when feature groups exist
    if feature_groups and ungrouped:
        idx = len(feature_groups) + 1
        lines.append(f"### M{idx:02d} -- Other changes")
        lines.append("")
        lines.append("| Task | File | Action | Summary |")
        lines.append("|---|---|---|---|")
        for task_idx, item in enumerate(ungrouped, 1):
            file_str = (
                ", ".join(str(f) for f in item.affected_files)
                if item.affected_files
                else "TBD"
            )
            lines.append(
                f"| {task_idx} | {file_str} | Update | {_item_description(item)} |"
            )
        lines.append("")

    # Open Questions
    questions: list[str] = []
    for item in impacts:
        title = _item_title(item)
        if not item.suggested_action:
            questions.append(f"What is the migration path for {title}?")
        if (
            isinstance(item.change, SchemaChange)
            and item.change.criticality == Criticality.BREAKING
            and not item.affected_files
        ):
            questions.append(
                f"Does this breaking change affect any unlisted files? ({title})"
            )

    if questions:
        lines.append("## Open Questions")
        lines.append("")
        for q in questions:
            lines.append(f"- [ ] {q}")
        lines.append("")

    return "\n".join(lines)
